const json=(data,status=200,headers={})=>Response.json(data,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...headers}});
const fail=(status,code)=>{throw Object.assign(new Error(code),{status})};
const hex=b=>Array.from(new Uint8Array(b),x=>x.toString(16).padStart(2,'0')).join('');
const random=()=>hex(crypto.getRandomValues(new Uint8Array(32)));
const digest=async s=>hex(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)));
async function passwordHash(password,salt){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);return hex(await crypto.subtle.deriveBits({name:'PBKDF2',salt:new TextEncoder().encode(salt),iterations:100000,hash:'SHA-512'},key,512))}
const equal=(a,b)=>{if(a.length!==b.length)return false;let n=0;for(let i=0;i<a.length;i++)n|=a.charCodeAt(i)^b.charCodeAt(i);return n===0};
const costs={detector:250,artifact:450,patch:100,pda:600,compass:180,badge:350,akm:420,viper:280,sunrise:350,seva:900,bear:380,veles:700,moonlight:550,sparkler:300};
const slots={akm:'weapon',viper:'weapon',sunrise:'armor',seva:'armor',bear:'detector',veles:'detector',moonlight:'artifact',sparkler:'artifact'};
const presets=new Set(['preset:0','preset:1','preset:2','preset:3']);
async function limit(db,key,max,ms){const now=Date.now();await db.prepare('INSERT INTO limits(key,count,expires) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN expires<? THEN 1 ELSE count+1 END,expires=CASE WHEN expires<? THEN ? ELSE expires END').bind(key,now+ms,now,now,now+ms).run();const row=await db.prepare('SELECT count FROM limits WHERE key=?').bind(key).first();if(row.count>max)fail(429,'RATE_LIMIT')}
async function body(req){if(Number(req.headers.get('content-length'))>100000)fail(413,'TOO_LARGE');const s=await req.text();if(s.length>100000)fail(413,'TOO_LARGE');try{return JSON.parse(s)}catch{fail(400,'INVALID_INPUT')}}
function text(v,min,max){if(typeof v!=='string'||v.trim().length<min||v.length>max)fail(400,'INVALID_INPUT');return v.trim()}
async function current(req,db){const token=(req.headers.get('cookie')||'').match(/(?:^|;\s*)sfc_session=([a-f0-9]{64})(?:;|$)/)?.[1];if(!token)return null;return db.prepare('SELECT u.* FROM users u JOIN sessions s ON s.user_id=u.id WHERE s.token=? AND s.expires>?').bind(await digest(token),Date.now()).first()}
async function profile(db,u){if(!u)return null;const rows=(await db.prepare('SELECT item_id,slot FROM inventory WHERE user_id=?').bind(u.id).all()).results;return {id:u.id,name:u.name,email:u.email,avatar:u.avatar,balance:u.balance,owned:rows.map(r=>r.item_id),equipmentSlots:Object.fromEntries(rows.filter(r=>r.slot).map(r=>[r.slot,r.item_id]))}}
const cookie=(req,token,age)=>`sfc_session=${token}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${age}${new URL(req.url).protocol==='https:'?'; Secure':''}`;
async function session(req,db,u){const token=random();await db.prepare('INSERT INTO sessions(token,user_id,expires) VALUES(?,?,?)').bind(await digest(token),u.id,Date.now()+7*86400000).run();return json({user:await profile(db,u)},200,{'Set-Cookie':cookie(req,token,604800)})}
async function reward(db,id,kind,amount){const day=new Date().toISOString().slice(0,10);const r=await db.prepare('INSERT INTO rewards(user_id,day,kind,count) VALUES(?,?,?,1) ON CONFLICT(user_id,day,kind) DO UPDATE SET count=count+1 WHERE count<3 RETURNING count').bind(id,day,kind).first();if(r)await db.prepare('UPDATE users SET balance=balance+? WHERE id=?').bind(amount,id).run()}
function validateContent(s){if(s.length>30000)fail(400,'INVALID_INPUT');return s}
export default {async fetch(req,env){try{const url=new URL(req.url),p=url.pathname,db=env.DB;if(!p.startsWith('/api/')&&!p.startsWith('/media/'))return env.ASSETS.fetch(req);
if(!db)return json({error:'DATABASE_UNAVAILABLE'},503);
if(!['GET','HEAD'].includes(req.method)){if(req.headers.get('Origin')!==url.origin)fail(403,'ORIGIN');if(!p.startsWith('/api/upload')&&!req.headers.get('content-type')?.includes('application/json'))fail(415,'INVALID_INPUT')}
if(p.startsWith('/media/')&&req.method==='GET'){const m=await db.prepare('SELECT mime FROM media WHERE id=?').bind(p.slice(7)).first();const object=m?await env.BUCKET.get(p.slice(7)):null;return object?new Response(object.body,{headers:{'Content-Type':m.mime,'X-Content-Type-Options':'nosniff','Cache-Control':'private,max-age=3600','Content-Security-Policy':"default-src 'none'"}}):new Response('Not found',{status:404})}
if(p==='/api/health')return json({ok:true});
const u=await current(req,db);
if(p==='/api/me'&&req.method==='GET')return json({user:await profile(db,u)});
if(p==='/api/bootstrap'&&req.method==='GET'){const [posts,replies,messages]=await Promise.all([db.prepare('SELECT p.*,u.name,u.avatar FROM posts p JOIN users u ON u.id=p.user_id ORDER BY p.id DESC LIMIT 1000').all(),db.prepare('SELECT r.*,u.name,u.avatar FROM replies r JOIN users u ON u.id=r.user_id ORDER BY r.id ASC LIMIT 5000').all(),db.prepare('SELECT m.*,u.name,u.avatar FROM messages m JOIN users u ON u.id=m.user_id ORDER BY m.id DESC LIMIT 60').all()]);return json({user:await profile(db,u),posts:posts.results.reverse(),replies:replies.results,messages:messages.results.reverse()})}
if((p==='/api/register'||p==='/api/login')&&req.method==='POST'){const b=await body(req),email=text(b.email,5,254).toLowerCase(),password=b.password; text(password,12,128);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))fail(400,'INVALID_EMAIL');const ip=req.headers.get('cf-connecting-ip')||'local';await limit(db,'auth-ip:'+await digest(ip),30,900000);await limit(db,'auth-email:'+await digest(email),10,900000);if(p==='/api/register'){const name=text(b.name,3,32);if(/[<>\[\]\x00-\x1f]/.test(name))fail(400,'INVALID_INPUT');const salt=random(),id=crypto.randomUUID(),hash=await passwordHash(password,salt);try{await db.prepare('INSERT INTO users(id,email,name,password,salt,created) VALUES(?,?,?,?,?,?)').bind(id,email,name,hash,salt,Date.now()).run()}catch(e){if(/unique/i.test(e.message))fail(409,'ACCOUNT_EXISTS');throw e}return session(req,db,await db.prepare('SELECT * FROM users WHERE id=?').bind(id).first())}const row=await db.prepare('SELECT * FROM users WHERE email=?').bind(email).first();const hash=await passwordHash(password,row?.salt||'dummy-salt-for-unknown-account');if(!row||!equal(hash,row.password))fail(401,'INVALID_LOGIN');return session(req,db,row)}
if(p==='/api/logout'&&req.method==='POST'){const token=(req.headers.get('cookie')||'').match(/sfc_session=([a-f0-9]{64})/)?.[1];if(token)await db.prepare('DELETE FROM sessions WHERE token=?').bind(await digest(token)).run();return json({ok:true},200,{'Set-Cookie':cookie(req,'',0)})}
if(!u)fail(401,'LOGIN_REQUIRED');
if(p==='/api/profile'&&req.method==='POST'){const b=await body(req),name=text(b.name,3,32),avatar=text(b.avatar,1,100);if(/[<>\[\]\x00-\x1f]/.test(name))fail(400,'INVALID_INPUT');if(!presets.has(avatar)){const m=avatar.match(/^\/media\/([a-f0-9-]+)$/);if(!m||!await db.prepare('SELECT id FROM media WHERE id=? AND user_id=?').bind(m[1],u.id).first())fail(400,'INVALID_AVATAR')}try{await db.prepare('UPDATE users SET name=?,avatar=? WHERE id=?').bind(name,avatar,u.id).run()}catch(e){if(/unique/i.test(e.message))fail(409,'ACCOUNT_EXISTS');throw e}return json({user:await profile(db,{...u,name,avatar})})}
if(p==='/api/upload'&&req.method==='POST'){await limit(db,'upload:'+u.id,20,3600000);if(Number(req.headers.get('content-length'))>800000)fail(413,'TOO_LARGE');const data=await req.arrayBuffer();if(data.byteLength>750000||data.byteLength<12)fail(413,'TOO_LARGE');const b=new Uint8Array(data);let mime;if(b[0]===137&&b[1]===80&&b[2]===78&&b[3]===71)mime='image/png';else if(b[0]===255&&b[1]===216&&b[2]===255)mime='image/jpeg';else if(String.fromCharCode(...b.slice(0,4))==='RIFF'&&String.fromCharCode(...b.slice(8,12))==='WEBP')mime='image/webp';else fail(415,'IMAGE_ONLY');const id=crypto.randomUUID();await env.BUCKET.put(id,data,{httpMetadata:{contentType:mime}});await db.prepare('INSERT INTO media(id,user_id,mime,created) VALUES(?,?,?,?)').bind(id,u.id,mime,Date.now()).run();return json({url:'/media/'+id})}
if(p==='/api/posts'&&req.method==='POST'){await limit(db,'post:'+u.id,12,3600000);const b=await body(req),title=text(b.title,5,100),content=validateContent(text(b.body,20,30000));if(!['news','forum','blog','screenshot'].includes(b.kind))fail(400,'INVALID_INPUT');if(b.kind==='screenshot'){const match=content.match(/^\[img\]\/media\/([a-f0-9-]+)\[\/img\]$/);if(!match||!await db.prepare('SELECT id FROM media WHERE id=? AND user_id=?').bind(match[1],u.id).first())fail(400,'INVALID_INPUT')}const board=text(b.board||'campfire',1,50);const row=await db.prepare('INSERT INTO posts(user_id,kind,board,title,body,created) VALUES(?,?,?,?,?,?) RETURNING id').bind(u.id,b.kind,board,title,content,Date.now()).first();await reward(db,u.id,b.kind==='screenshot'?'screenshot':'post',b.kind==='screenshot'?15:30);return json(row,201)}
if(p==='/api/replies'&&req.method==='POST'){await limit(db,'reply:'+u.id,30,3600000);const b=await body(req),thread=text(b.thread,2,90);if(!/^(post\d+|discussion[a-z0-9_-]+|article\d+)$/.test(thread))fail(400,'INVALID_INPUT');if(thread.startsWith('post')&&!await db.prepare('SELECT id FROM posts WHERE id=?').bind(Number(thread.slice(4))).first())fail(404,'NOT_FOUND');await db.prepare('INSERT INTO replies(user_id,thread,body,created) VALUES(?,?,?,?)').bind(u.id,thread,validateContent(text(b.body,5,30000)),Date.now()).run();await reward(db,u.id,'comment',5);return json({ok:true},201)}
if(p==='/api/messages'&&req.method==='POST'){await limit(db,'chat:'+u.id,30,60000);const b=await body(req);await db.prepare('INSERT INTO messages(user_id,body,created) VALUES(?,?,?)').bind(u.id,text(b.body,1,500),Date.now()).run();return json({ok:true},201)}
if(p==='/api/buy'&&req.method==='POST'){const b=await body(req),price=costs[b.id];if(!price)fail(400,'INVALID_INPUT');if(await db.prepare('SELECT item_id FROM inventory WHERE user_id=? AND item_id=?').bind(u.id,b.id).first())fail(409,'ALREADY_OWNED');const results=await db.batch([db.prepare('UPDATE users SET balance=balance-? WHERE id=? AND balance>=? AND NOT EXISTS(SELECT 1 FROM inventory WHERE user_id=? AND item_id=?)').bind(price,u.id,price,u.id,b.id),db.prepare('INSERT OR IGNORE INTO inventory(user_id,item_id) SELECT ?,? WHERE changes()=1').bind(u.id,b.id)]);if(!results[0].meta.changes)fail(409,'INSUFFICIENT');return json({ok:true})}
if(p==='/api/equip'&&req.method==='POST'){const b=await body(req);if(!costs[b.id]||!await db.prepare('SELECT item_id FROM inventory WHERE user_id=? AND item_id=?').bind(u.id,b.id).first())fail(400,'NOT_OWNED');const slot=slots[b.id]||b.id;await db.batch([db.prepare('UPDATE inventory SET slot=NULL WHERE user_id=? AND slot=?').bind(u.id,slot),db.prepare('UPDATE inventory SET slot=? WHERE user_id=? AND item_id=?').bind(b.equip?slot:null,u.id,b.id)]);return json({ok:true})}
return json({error:'NOT_FOUND'},404);
}catch(e){if(!e.status)console.error('Community request failed',e.message);return json({error:e.status?e.message:'SERVER_ERROR'},e.status||500)}}};
